// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv9kWcujz4MHZFs6qm-DXEDRd6EevW4tQ',
    appId: '1:349602176987:web:8599624f398567be89d1fe',
    messagingSenderId: '349602176987',
    projectId: 'mai-escrow',
    authDomain: 'mai-escrow.firebaseapp.com',
    storageBucket: 'mai-escrow.firebasestorage.app',
    measurementId: 'G-35ET8PZSSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG_RPKhPG6fvSLchU-3FugHdFoyy3EOEw',
    appId: '1:349602176987:android:4ade93eeb0400c9f89d1fe',
    messagingSenderId: '349602176987',
    projectId: 'mai-escrow',
    storageBucket: 'mai-escrow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT63SFUYVCukVICPzpsRFv7nHLupoOdlE',
    appId: '1:349602176987:ios:8bbc90d8cd352c5389d1fe',
    messagingSenderId: '349602176987',
    projectId: 'mai-escrow',
    storageBucket: 'mai-escrow.firebasestorage.app',
    iosBundleId: 'mai.app.escrow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT63SFUYVCukVICPzpsRFv7nHLupoOdlE',
    appId: '1:349602176987:ios:c0fc1e2432c02e1a89d1fe',
    messagingSenderId: '349602176987',
    projectId: 'mai-escrow',
    storageBucket: 'mai-escrow.firebasestorage.app',
    iosBundleId: 'com.app.escrow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv9kWcujz4MHZFs6qm-DXEDRd6EevW4tQ',
    appId: '1:349602176987:web:59c208426ca5bf0089d1fe',
    messagingSenderId: '349602176987',
    projectId: 'mai-escrow',
    authDomain: 'mai-escrow.firebaseapp.com',
    storageBucket: 'mai-escrow.firebasestorage.app',
    measurementId: 'G-M78BDRMQ2T',
  );
}
